#!/bin/bash
# Setup script for Daru PDF GCP Infrastructure
#
# This script initializes the GCP project with required APIs,
# service accounts, and Terraform state bucket.
#
# Usage: ./setup.sh [PROJECT_ID] [REGION]

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
DEFAULT_REGION="asia-northeast1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="${SCRIPT_DIR}/../terraform"

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

check_dependencies() {
    log_info "Checking dependencies..."

    if ! command -v gcloud &> /dev/null; then
        log_error "gcloud CLI is not installed. Please install it from https://cloud.google.com/sdk/docs/install"
    fi

    if ! command -v terraform &> /dev/null; then
        log_error "Terraform is not installed. Please install it from https://www.terraform.io/downloads.html"
    fi

    log_success "All dependencies are installed"
}

get_project_id() {
    if [ -n "${1:-}" ]; then
        PROJECT_ID="$1"
    else
        PROJECT_ID=$(gcloud config get-value project 2>/dev/null)
        if [ -z "$PROJECT_ID" ]; then
            log_error "No project ID specified and no default project set. Use: ./setup.sh PROJECT_ID"
        fi
    fi
    echo "$PROJECT_ID"
}

enable_apis() {
    local project_id="$1"
    log_info "Enabling required APIs for project: $project_id"

    local apis=(
        "run.googleapis.com"
        "vpcaccess.googleapis.com"
        "redis.googleapis.com"
        "storage.googleapis.com"
        "artifactregistry.googleapis.com"
        "secretmanager.googleapis.com"
        "cloudresourcemanager.googleapis.com"
        "compute.googleapis.com"
        "cloudbuild.googleapis.com"
    )

    for api in "${apis[@]}"; do
        log_info "Enabling $api..."
        gcloud services enable "$api" --project="$project_id" --quiet
    done

    log_success "All APIs enabled"
}

create_terraform_state_bucket() {
    local project_id="$1"
    local region="$2"
    local bucket_name="${project_id}-terraform-state"

    log_info "Creating Terraform state bucket: $bucket_name"

    if gsutil ls -b "gs://${bucket_name}" &> /dev/null; then
        log_warning "Bucket $bucket_name already exists"
    else
        gsutil mb -p "$project_id" -l "$region" "gs://${bucket_name}"
        gsutil versioning set on "gs://${bucket_name}"
        log_success "Terraform state bucket created"
    fi
}

create_artifact_registry() {
    local project_id="$1"
    local region="$2"
    local repo_name="daru-pdf"

    log_info "Creating Artifact Registry repository: $repo_name"

    if gcloud artifacts repositories describe "$repo_name" \
        --location="$region" \
        --project="$project_id" &> /dev/null; then
        log_warning "Repository $repo_name already exists"
    else
        gcloud artifacts repositories create "$repo_name" \
            --repository-format=docker \
            --location="$region" \
            --project="$project_id" \
            --description="Container images for Daru PDF services"
        log_success "Artifact Registry repository created"
    fi
}

configure_docker_auth() {
    local region="$1"
    log_info "Configuring Docker authentication for Artifact Registry"
    gcloud auth configure-docker "${region}-docker.pkg.dev" --quiet
    log_success "Docker authentication configured"
}

initialize_terraform() {
    log_info "Initializing Terraform..."

    cd "$TERRAFORM_DIR"
    terraform init

    log_success "Terraform initialized"
}

create_tfvars_template() {
    local project_id="$1"
    local region="$2"
    local tfvars_file="${TERRAFORM_DIR}/terraform.tfvars"

    log_info "Creating terraform.tfvars template"

    if [ -f "$tfvars_file" ]; then
        log_warning "terraform.tfvars already exists, skipping..."
    else
        cat > "$tfvars_file" << EOF
# Daru PDF GCP Infrastructure Variables
# Generated by setup.sh

project_id  = "${project_id}"
region      = "${region}"
environment = "dev"

# Service Images (update after building)
# api_image          = "${region}-docker.pkg.dev/${project_id}/daru-pdf/api:latest"
# web_image          = "${region}-docker.pkg.dev/${project_id}/daru-pdf/web:latest"
# orchestrator_image = "${region}-docker.pkg.dev/${project_id}/daru-pdf/orchestrator:latest"

# Cloud Run Configuration
api_cpu           = "2"
api_memory        = "4Gi"
api_min_instances = 0
api_max_instances = 10
api_timeout       = 300

web_cpu           = "1"
web_memory        = "1Gi"
web_min_instances = 1
web_max_instances = 3

orchestrator_cpu           = "1"
orchestrator_memory        = "2Gi"
orchestrator_min_instances = 0
orchestrator_max_instances = 5

# Memorystore Configuration
redis_tier           = "BASIC"
redis_memory_size_gb = 1

# Storage Configuration
storage_location       = "ASIA-NORTHEAST1"
storage_lifecycle_days = 30
storage_delete_days    = 90

# External Services (SENSITIVE - use environment variables or Secret Manager)
# supabase_url         = ""
# supabase_service_key = ""
# supabase_anon_key    = ""
# openai_api_key       = ""
EOF
        log_success "terraform.tfvars template created. Please update with your values."
    fi
}

print_next_steps() {
    local project_id="$1"
    local region="$2"

    echo ""
    echo "=============================================="
    echo -e "${GREEN}Setup Complete!${NC}"
    echo "=============================================="
    echo ""
    echo "Next steps:"
    echo ""
    echo "1. Update terraform.tfvars with your configuration:"
    echo "   cd ${TERRAFORM_DIR}"
    echo "   vim terraform.tfvars"
    echo ""
    echo "2. Set sensitive variables (Supabase, OpenAI keys):"
    echo "   export TF_VAR_supabase_url='your-supabase-url'"
    echo "   export TF_VAR_supabase_service_key='your-service-key'"
    echo "   export TF_VAR_openai_api_key='your-openai-key'"
    echo ""
    echo "3. Plan and apply Terraform:"
    echo "   terraform plan"
    echo "   terraform apply"
    echo ""
    echo "4. Build and deploy services:"
    echo "   ./deploy.sh all"
    echo ""
    echo "Artifact Registry URL:"
    echo "   ${region}-docker.pkg.dev/${project_id}/daru-pdf"
    echo ""
}

# Main
main() {
    echo "=============================================="
    echo "Daru PDF GCP Infrastructure Setup"
    echo "=============================================="
    echo ""

    check_dependencies

    PROJECT_ID=$(get_project_id "${1:-}")
    REGION="${2:-$DEFAULT_REGION}"

    log_info "Project ID: $PROJECT_ID"
    log_info "Region: $REGION"
    echo ""

    enable_apis "$PROJECT_ID"
    create_terraform_state_bucket "$PROJECT_ID" "$REGION"
    create_artifact_registry "$PROJECT_ID" "$REGION"
    configure_docker_auth "$REGION"
    initialize_terraform
    create_tfvars_template "$PROJECT_ID" "$REGION"

    print_next_steps "$PROJECT_ID" "$REGION"
}

main "$@"
