"""API contract models for the Review service.

All models use frozen=True for immutability, following project conventions.
These models define the input/output contract for the POST /review endpoint.
"""

from pydantic import BaseModel, Field

from app.models.field import FieldModel
from app.models.job import Issue


class PageMetaInput(BaseModel):
    """Metadata for a page in the review request.

    Provides page dimensions and rotation for accurate
    coordinate mapping and rendering.
    """

    page_number: int = Field(..., ge=1, description="1-indexed page number")
    width: float = Field(..., gt=0, description="Page width in points")
    height: float = Field(..., gt=0, description="Page height in points")
    rotation: int = Field(
        default=0,
        ge=0,
        le=270,
        description="Page rotation in degrees (0, 90, 180, 270)",
    )

    model_config = {"frozen": True}


class PreviewArtifact(BaseModel):
    """A preview image artifact generated by the review.

    Contains references to rendered page images and optional
    diff images for visual comparison.
    """

    page: int = Field(..., ge=1, description="1-indexed page number")
    preview_ref: str = Field(..., description="Storage reference for preview image")
    preview_url: str = Field(..., description="URL to access preview image")
    diff_ref: str | None = Field(
        default=None,
        description="Storage reference for diff image (if generated)",
    )
    diff_url: str | None = Field(
        default=None,
        description="URL to access diff image (if generated)",
    )
    width: int = Field(..., gt=0, description="Preview image width in pixels")
    height: int = Field(..., gt=0, description="Preview image height in pixels")
    field_count: int = Field(
        default=0,
        ge=0,
        description="Number of fields on this page",
    )

    model_config = {"frozen": True}


class ConfidenceUpdate(BaseModel):
    """Update to a field's confidence score based on review findings.

    When issues are detected (overflow, overlap), the confidence
    in the field extraction is reduced accordingly.
    """

    field_id: str = Field(..., description="ID of the field being updated")
    original_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Original confidence before review",
    )
    updated_confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Updated confidence after review",
    )
    reason: str = Field(..., description="Reason for confidence change")

    model_config = {"frozen": True}


class ReviewRequest(BaseModel):
    """Request to review a filled document.

    Provides the filled document reference, field definitions,
    and optional original document for diff generation.

    Input contract for POST /review endpoint.
    """

    document_id: str = Field(
        ...,
        min_length=1,
        description="Unique document identifier",
    )
    filled_document_ref: str = Field(
        ...,
        min_length=1,
        description="Reference/path to the filled PDF file",
    )
    original_document_ref: str | None = Field(
        default=None,
        description="Reference/path to original PDF (for diff generation)",
    )
    fields: list[FieldModel] = Field(
        default_factory=list,
        description="Fields to check for issues",
    )
    page_meta: list[PageMetaInput] = Field(
        default_factory=list,
        description="Page metadata for coordinate mapping",
    )
    render_dpi: int = Field(
        default=150,
        gt=0,
        le=600,
        description="DPI for preview rendering",
    )
    default_font_size: float = Field(
        default=12.0,
        gt=0,
        description="Default font size for overflow detection",
    )
    generate_diff: bool = Field(
        default=True,
        description="Whether to generate diff images",
    )

    model_config = {"frozen": True}


class ReviewResult(BaseModel):
    """Result of reviewing a filled document.

    Contains detected issues, preview artifacts, and
    confidence updates.

    Output contract for POST /review endpoint.
    """

    document_id: str = Field(..., description="Document identifier from request")
    success: bool = Field(..., description="Whether review completed successfully")
    issues: tuple[Issue, ...] = Field(
        default=(),
        description="Detected issues (immutable tuple)",
    )
    preview_artifacts: tuple[PreviewArtifact, ...] = Field(
        default=(),
        description="Generated preview images (immutable tuple)",
    )
    confidence_updates: tuple[ConfidenceUpdate, ...] = Field(
        default=(),
        description="Confidence score updates (immutable tuple)",
    )
    total_issues: int = Field(
        default=0,
        ge=0,
        description="Total number of issues detected",
    )
    critical_issues: int = Field(
        default=0,
        ge=0,
        description="Number of critical/high severity issues",
    )
    error: str | None = Field(
        default=None,
        description="Error message if review failed",
    )

    model_config = {"frozen": True}
